### ISSUE TITLE
PvpScript spits out a error

### ISSUE THREAD

**Issue by mw-voo** [brandonsturgeon/PlayerPvP#4]
```
[ERROR] addons/pvpscript/lua/autorun/server/sv_pvpscript.lua:151: Tried to use a NULL entity!
  1. RemovePlayer - [C]:-1
   2. unknown - addons/pvpscript/lua/autorun/server/sv_pvpscript.lua:151
```

**Comment by brandonsturgeon** [comment]
This is fine, it happens when someone types !pvpoff and then leaves the server. No biggy.

**Comment by brandonsturgeon** [comment]
We should think about refactoring the way pvp is turned on and off. Timers are not great. Maybe a list of people who want to enter/exit pvp mode, along with the time they requested it, and we can loop through the list once every 0.5 seconds and do business accordingly.

**Comment by brandonsturgeon** [comment]
Moved this into https://github.com/brandonsturgeon/PlayerPvP/issues/5
